services:
  pg:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=wb
      - POSTGRES_PASSWORD=wb
      - POSTGRES_DB=wb
    ports:
      - 5432:5432
    volumes:
      - './db/pg/orders.sql:/docker-entrypoint-initdb.d/orders.sql'

  streaming:
      image: nats-streaming:latest
      ports:
        - "4222:4222"